#+title: Doom Emacs configuration
#+PROPERTY: tangle "config.el"

* Introduction
* General settings
** User identification
#+begin_src elisp
(setq user-full-name "Patrick Grogan"
      user-mail-address "po.grogan@gmail.com")
#+end_src
** Startup performances
These are some improvement now the we are all using modern computers
#+begin_src elisp
(setq gc-cons-threshold (* 50 1000 1000))
#+end_src
** Visuals
I am using two fonts for Emacs. My mono font is [[https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraCode/Retina/complete][Nerd Font FiraCode Retina]]  and my varibale pitched font is [[https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Overpass/Non-Mono/Regular/complete][ Nerd Font Overpass]]. I will also make sure the that text-mode will use mixed pitch to have normal text using the variable width while code block will be using the monospace one.
#+begin_src elisp
(setq doom-font (font-spec :family "FiraCode Nerd Font Mono" :size 16)
      doom-variable-pitch-font (font-spec :family "Overpass Nerd Font" :size 16))
;; Make sure text-mode uses variable pitch for non code
(add-hook! 'text-mode-hook (mixed-pitch-mode))
#+end_src
For a theme, gruv-box with a darker theme!
#+begin_src elisp
(setq doom-gruvbox-dark-variant 'hard
      doom-gruvbox-brighter-comments nil
      doom-theme 'doom-gruvbox)
#+end_src
Relative line numbers make it so much easier to jump on the line you want to without thinking too much!
#+begin_src elisp
(setq display-line-numbers-type 'relative)
#+end_src
* Package Configuration
** Org
Just prettier bullets!
#+begin_src elisp
(setq org-superstar-headline-bullets-list '("⁖" "◉" "○" "✸" "✿"))
#+end_src
Org mode files are placed here!
#+begin_src elisp
(setq org-directory "~/org/")
#+end_src

Template block enables the use of >el to create a code block of elisp.
#+begin_src elisp
(require 'org-tempo)
(add-to-list 'org-structure-template-alist '("el" . "src elisp"))
(add-to-list 'org-structure-template-alist '("py" . "src python"))
(add-to-list 'org-structure-template-alist '("sh" . "src bash"))
(add-to-list 'org-structure-template-alist '("sv" . "src verilog"))
#+end_src

** Projectile
We are adding search path to projectile for typical projects location. My preference is workspace but as of right now, I need to place some work related stuff in ~/projects because scripts depend on it.
#+begin_src elisp
(setq projectile-project-search-path '("~/projects/" ("~/workspace/" . 1) "~/dotfiles"))
#+end_src
* Languages
** Javascript
#+begin_src elisp
(add-hook! js-mode #'tree-sitter-mode)
#+end_src
** Python
For python, we will be using treesitter mode for syntax highlighting. It is WAY better and faster than pure regex engine.
#+begin_src elisp
(add-hook! python-mode #'tree-sitter-mode)
#+end_src
** Rust
#+begin_src elisp
(add-hook! rust-mode #'tree-sitter-mode)
#+end_src
** Verilog/Systemverilog
What is wrong with people... default indent is weird... reseting it to sane defaults
#+begin_src elisp
(setq verilog-case-indent 4
      verilog-cexp-indent 4
      verilog-indent-level 4
      verilog-indent-level-behavioral 4
      verilog-indent-level-declaration 4
      verilog-indent-level-directive 4
      verilog-indent-level-module 4
      verilog-indent-lists nil
      verilog-indent-begin-after-if t)
#+end_src
